# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YJWeibo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YJWeibo
    platform :ios, '9.0'
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'SVProgressHUD'

  target 'YJWeiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJWeiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
